# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.5"
  - "3.4"

env:
  - DJANGO_VERSION=1.8.15
  - DJANGO_VERSION=1.9.10
  - DJANGO_VERSION=1.10.2

matrix:
  include:
    - python: "3.3"
      env: DJANGO_VERSION=1.8.15

    - python: "3.5"
      env: TEST_PEP8=True
      install: pip install flake8
      script: flake8 konfera

before_install:
  - pip install codecov

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install coverage

# command to run tests using coverage, e.g. python setup.py test
script: coverage run --source konfera runtests.py

after_success:
  - codecov

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2f5f7550882030346bca
    on_success: change
    on_failure: always
    on_start: never
  slack: django-konfera:b9GUe4UHZMg4VnwuxbiOA0Yo
